<div class="grid-x grid-margin-x">
    <?php include 'stavka.phtml'; ?>
</div>



<div class="reveal" id="slikaModal" data-reveal>
  <img id="image" src="" alt="" />
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremi">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>