<!-- Početak izbornik -->
<h1 style="text-align: center;background-color: rgb(190, 57, 9);color: rgba(255, 255, 255, 0.534);font-weight: bold;">GRILL & CHILL</h1>
<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title" style="background-color: orange;"><?php echo APP::config('nazivAPP'); ?></div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out" >
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu > 
            <li class="menu-text show-for-large">
            <?php echo APP::config('nazivAPP'); ?>
            </li>
            <li><a href="/">Početna</a></li>
            <?php if(isset($_SESSION['korisnik'])):?>
                <?php if($_SESSION['korisnik']->status==='admin'):?>
                    <li><a href="/korisnici/index">Korisnici</a></li>
                    <li><a href="#">Upravljanje podacima</a>
                        <ul class="vertical menu">
                            <li><a href="/kategorija/index">Kategorije</a></li>
                            <li><a href="/status/index">Status</a></li>
                            <li><a href="/stol/index">Stolovi</a></li>
                        </ul>
                    </li>
                <?php else:?>
                    <li><a href="/profil/index">Profil</a></li>
                <?php endif;?>
                
                <li><a href="/ponuda/trazi?uvjet=Juha">Menu</a>
                
                <ul class="vertical menu">
                <?php foreach (  $meniKategorije as $red ) {  ?> 
                    <li><a href="/ponuda/trazi?uvjet=<?php echo $red->nazivKat;?>"><?php echo $red->nazivKat;?></a></li>
               <?php } ?>                       
                </ul>
                </li>
                <!-- Kraj MENUa -->  
                <?php endif;?>

            
            <?php if(isset($_SESSION['korisnik']) && $_SESSION['korisnik']->status==='gost'):?>
            <li><a href="/kosara/index">Košara</a></li>
            <?php elseif(isset($_SESSION['korisnik'])):?>
                <li><a href="/narudzba/index">Narudžbe</a></li>
            <?php endif;?>
            <li><a href="/index/onama">O nama</a></li>
            <li><a href="/index/ERA">ERA</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
        <?php if(isset($_SESSION['korisnik']) && $_SESSION['korisnik']->status==='gost'):?>
            <li><a href="#">Grill bodovi: 0</a></li>
            <?php endif;?>
            <li>
            <?php if(!isset($_SESSION['korisnik'])): ?>
                <a href="/index/prijava">Prijava</a>
            <?php else:?>
                <a href="/index/odjava">Odjavi se</a>
            <?php endif;?>
            </li>
        </ul>
    </div>
</div>
<!-- Kraj izbornik -->