
<tr> 
    <td style="text-align: left;" title="Jelo"><?php echo $ponuda->naziv?></td>
    <td style="text-align: left;" title="Kolicina">

 
<a id="<?php echo $ponuda->kosara_sifra . '_' . $ponuda->ponuda_sifra ?>" 
class="button otvoriModalKolicina"style="background-color: orange; padding:15px; width: 200px; font-size: 20px;">
<?php echo $ponuda->kolicina ?></a>


    </td>

    <td title="Ukloni">
    <a href="/narudzba/obrisiPonudu?sifra=<?php echo $ponuda->ponuda_sifra ?>&sifraKos=<?php echo $narudzba->sifraKos?>">
    <i class="fas fa-trash fa-2x" style="color: orange;"></i></a></td> 
</tr>



<div class="reveal" id="modalKolicina" data-reveal>
  <p>Promjeni količinu </p>
  <select id="kol">
        <?php for($i=1;$i<10;$i++){   ?>
        <option value="<?php echo $i ?>"><?php echo $i ?></option>    
        <?php } ?>
</select>
  <a id="linkKolicina" class="button">DA</a>
  <a id="odustani" class="button">Odustani</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>



