 
<tr class="flip" id="g_<?php echo $red->sifra?>"> 
    <td title="Broj narudžbe"><?php echo $red->sifra?></td>
    <td style="text-align: left;" title="Cijena"><?php echo $red->cijena?></td>
    <td style="text-align: left;" title="Stol"><?php echo $red->stol?></td>
    <td style="text-align: left;" title="Status"><?php echo $red->status?></td> 
    
</tr>

<tbody class="panel" id="g_<?php echo $red->sifra?>">
<tr >
    <td title="Broj narudžbe">Jsfasfa</td>
    <td style="text-align: left;" title="Cijena">Naziv</td>
    <td style="text-align: left;" title="Stol">Kolicina</td>
    <td style="text-align: left;" title="Status">Cijena</td>
    <td style="text-align: left;" title="Status">Vrijeme</td>  
</tr>
</tbody>