<tr>
    <td title="Broj narudžbe"><?php echo $red->sifra?></td>
    <td title="Hrana"><?php echo $red->ponuda?></td>
    <td style="text-align: left;" title="Cijena"><?php echo $red->cijena?></td>
    <td style="text-align: left;" title="Konobar"><?php echo $red->konobar?></td>
    <td style="text-align: left;" title="Stol"><?php echo $red->stol?></td>
    <td style="text-align: left;" title="Status"><?php echo $red->status?></td>
    
    
</tr>

