<form class="log-in-form" method="POST" action="/ponuda/dodajnovo">


  <label> Naziv <input type="text" id="naziv" name="naziv"> </label>
  <label> Slika <input type="text" id="slika" name="slika"> </label>
  <label> Opis <input type="text" id="opis" name="opis"> </label>
  <label> Vrijeme <input type="number" id="vrijeme" name="vrijeme"> </label>

  <label for="kategorija">Kategorija</label>
  <select name="kategorija" id="kategorija">

  <?php 
  foreach($meniKategorije as $kategori){   ?>

<option value="<?php echo $kategori->sifra ?>"><?php echo $kategori->nazivKat ?></option>
<?php } ?>
  </select>

  <label> Cijena <input type="number" id="cijena" name="cijena"> </label>
  
  <p><input type="submit" class="button expanded" value="Dodaj jelo"></input></p>
</form>
<?php echo $poruka; ?>