<form class="log-in-form" method="POST"
action="/ponuda/promjeni?sifra=<?php echo $jelo->sifra ?>">

  <label>Naziv
    <input type="text" id="naziv" name="naziv" value="<?php 
    echo $jelo->naziv;
    ?>">
  </label>

  <label>Slika
    <input type="text" id="slika" name="slika" value="<?php 
    echo $jelo->slika;
    ?>">
  </label>

  <label>Opis
    <input type="text" id="opis" name="opis" value="<?php 
    echo $jelo->opis;
    ?>">
  </label>

  <label>Vrijeme
    <input type="number" id="vrijeme" name="vrijeme" value="<?php 
    echo $jelo->vrijeme;
    ?>">
  </label>


  <label for="kategorija">Kategorija</label>
  <select name="kategorija" id="kategorija">

  <?php 
  foreach($meniKategorije as $kategori){   ?>

<option value="<?php echo $kategori->sifra ?>"><?php echo $kategori->nazivKat ?></option>
<?php } ?>
  </select>
 

  <label>Cijena
    <input type="number" id="cijena" name="cijena" value="<?php 
    echo $jelo->cijena;
    ?>">
  </label>

  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/ponuda/index" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Promjeni podatke"></input>
    </div>
  </div>
</form>
<?php echo $poruka; ?>