<tr>
<td title="slika"> <img src="<?php echo $red->slika?>"></td>
    <td title="naziv" >
        <span style="font-size: 1.4em;"> <h3><?php echo $red->naziv?></h3> <?php echo $red->opis?></span>
    </td>
    <td style="text-align: left;" title="vrijeme"><?php echo $red->vrijeme . ' min';?></td>
    <td style="text-align: left;" title="kategorija"><?php echo $red->nazivKat?></td>
    <td style="text-align: left;" title="cijena"><?php echo $red->cijena . 'kn'?></td>
    <td>
    <?php 
    if($_SESSION['korisnik']->status==='admin')
    { ?>
     
    <!-- Uređivanje jela -->
    <a href="/ponuda/promjena?sifra=<?php echo $red->sifra ?>">
    <i class="fas fa-pencil-alt fa-2x" style="color: orange;" title="Izmjeni"></i></a>
        
    <!-- Brisanje jela -->
    <a onclick="return confirm('Sigurno zelis obrisati <?php echo $red->naziv ?> ');" 
    href="/ponuda/obrisi?sifra=<?php echo $red->sifra ?>">
    <i class="far fa-times-circle fa-2x" style="color: orange;" title="Ukloni"></i></a>

    <?php 
    } elseif($_SESSION['korisnik']->status==='gost')
    {?>

    <i id="<?php echo $red->sifra . '_' . $red->nazivKat ?>" 
    class="fas fa-drumstick-bite fa-2x" style="color: orange; cursor: pointer;" ></i> 
    
    <?php 
    }?>
    </td>
</tr>

<div class="reveal" id="modalDodaj" data-reveal>
  <h3 id="pitanje"></h3>
  <select id="kolicina" >
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
  </select>
  <a id="linkDodavanje" class="button">DA</a>
  <a id="odustani" class="button">NE</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>


