<tr>
<td title="slika"> <!-- <img src="<?php// echo $red->slika?>"> -->
        <?php
            if(file_exists(BP . 'public' . DIRECTORY_SEPARATOR
            . 'images' . DIRECTORY_SEPARATOR . 
            'ponuda' . DIRECTORY_SEPARATOR 
            . $red->sifra . '.png')):
        ?> 
        <img <?php if($_SESSION['korisnik']->status=="admin") echo 'class="slikaPonude"'?>  
        id="p_<?php echo $red->sifra ?>" style="max-width: 200px" 
        src="<?php echo APP::config('url'); ?>public/images/ponuda/<?php echo $red->sifra; ?>.png" 
        alt="<?php echo $red->naziv . ' ' . $red->nazivKat ?>" />
            <?php else:?>
                <img <?php if($_SESSION['korisnik']->status=="admin") echo 'class="slikaPonude"'?>  
                id="p_<?php echo $red->sifra ?>" style="max-width: 200px"
                src="<?php echo APP::config('url'); ?>public/images/bezslike.jpg"  
                alt="Za polaznika nije postavljena slika" />  <!-- Ubaciti gore sliku umjesto nepoznato.jpg -->
            <?php endif;?>


</td>
    <td title="naziv" >
        <span style="font-size: 1.4em;"> <h3><?php echo $red->naziv?></h3> <?php echo $red->opis?></span>
    </td>
    <td style="text-align: left;" title="vrijeme"><?php echo $red->vrijeme . ' min';?></td>
    <td style="text-align: left;" title="kategorija"><?php echo $red->nazivKat?></td>
    <td style="text-align: left;" title="cijena"><?php echo $red->cijena . 'kn'?></td>
    <td>
    <?php 
    if($_SESSION['korisnik']->status==='admin')
    { ?>
     
    <!-- Uređivanje jela -->
    <a href="/ponuda/promjena?sifra=<?php echo $red->sifra ?>">
    <i class="fas fa-pencil-alt fa-2x" style="color: orange;" title="Izmjeni"></i></a>
        
    <!-- Brisanje jela -->
    <a onclick="return confirm('Sigurno zelis obrisati <?php echo $red->naziv ?> ');" 
    href="/ponuda/obrisi?sifra=<?php echo $red->sifra ?>">
    <i class="far fa-times-circle fa-2x" style="color: orange;" title="Ukloni"></i></a>

    <?php 
    } elseif($_SESSION['korisnik']->status==='gost')
    {?>

    <i id="<?php echo $red->sifra . '_' . $red->nazivKat ?>" 
    class="fas fa-drumstick-bite fa-2x" style="color: orange; cursor: pointer;" ></i> 
    
    <?php 
    }?>
    </td>
</tr>

<div class="reveal" id="modalDodaj" data-reveal>
  <h3 id="pitanje"></h3>
  <p>Odaberite količinu</p>
  <select id="kolicina" >
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
  </select>
  <a id="linkDodavanje" class="button">DA</a>
  <a id="odustani" class="button">NE</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
 

 
<div class="reveal" id="slikaPonudeModal" data-reveal>
  <img id="image" src="" alt="" />
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremiSliku">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

