<?php 
    if($_SESSION['korisnik']->status==='admin')
    { ?>
    <a class="button expanded" style="background-color: orange;" href="/korisnici/novi">Dodaj korisnika</a>
    <?php
    }?>

    <a href="/korisnici/popis" class="button" style="background-color: orange;">Cijeli popis korisnika</a>

<div class="large-6 cell">
    <label for="uvjet">Prikaži korisnika</label>
    <input type="text" id="uvjet" />
    <div style="width: 100%; overflow: auto; max-height: 380px;"></div>
</div>


<div id="AjaxTest"></div>



