<form class="log-in-form" method="POST"
action="/korisnici/dodajnovog">
 <label>Email
    <input type="email" id="email" name="email" value="<?php 
    echo isset($_POST['email']) ? $_POST['email'] : '' 
    ?>">
  </label>

  <label>Password
    <input type="password" id="lozinka" name="lozinka">
  </label>

  <label>Password ponovo
    <input type="password" id="lozinkaponovo" name="lozinkaponovo">
  </label>

  <label>Ime
    <input type="text" id="ime" name="ime" value="<?php 
    echo isset($_POST['ime']) ? $_POST['ime'] : '' 
    ?>">
  </label>

  <label>Prezime
    <input type="text" id="prezime" name="prezime" value="<?php 
    echo isset($_POST['prezime']) ? $_POST['prezime'] : '' 
    ?>">
  </label>

  <label for="status">Status</label>
  <select name="status" id="status">
    <option value="gost">Gost</option>
    <option value="konobar">Konobar</option>
    <option value="kuhar">Kuhar</option>
    <option value="zastitar">Zastitar</option>
    <option value="admin">Administrator</option>
  </select>

  <p><input type="submit" class="button expanded" value="Dodaj operatera"></input></p>
</form>
<?php echo $poruka; ?>